### ISSUE TITLE
关于该门课程的推荐教材

### ISSUE THREAD

**Issue by SimZD** [PeterTheSparrow/SE3330-Principles-and-practice-of-software-engineering-2023-Notes#1]
软件工程书籍与教材繁多，想请问一下，该门课程的教材是是哪一位作者的哪一本书籍呢？
若能不吝赐教，万分感激。

**Comment by PeterTheSparrow** [comment]
本门课程教材是上海交通大学软件学院沈备军老师编写的《软件工程原理与实践》。本人作为本科生，才疏学浅，也未曾接触过特别多软件工程原理方面的书籍和课程，或许也有更经典、优秀的国外课程、书籍可供选择使用。祝好。
